# Generated by Django 3.1.1 on 2020-10-30 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0006_auto_20201029_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('NOJ', 'Не ищу работу'), ('OFF', 'Рассматриваю предложения'), ('LJ', 'Ищу работу')], default='NOJ', max_length=3)),
                ('salary', models.IntegerField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.TextField()),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='vacancies.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
